name: Manually trigger Workflow workflow_dispatch

on:
  workflow_dispatch:
env:
  greetings: hello world
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "$greetings, This is a manually triggered workflow."