name: Repository Dispatch Example

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  dispatch_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: 'echo "Repository dispatch triggered with event: ${{ github.event.action }}"'