name: webhook event example

on:
  repository_dispatch:
    types: 
       - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: 'echo "Repository dispatch triggered with event of type: $GITHUB_EVENT_NAME"'