name : java maven build publish ARTIFACT

on : 
  push:
    branches: [ main]
  pull_request:
    branches: [main]


jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up jdk 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml


  publish-job: 
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*.jar staging 
      - uses: actions/upload-artifact@v3
        with: 
         name: Package
         path: staging 