name : my python workflow 
on:
 push:
   branches: [main]
 pull_request:
   branches: [main]
env:
   DAY_OF_WEEK: Thursday    
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env: 
      greetings: hello
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: run python script
        run: |
            python python_scripts/python1.py
            echo "$greetings, world  today is $DAY_OF_WEEK"
       
            