name: CI/CD Pipeline using secret

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: |
         npm init -y
         npm install
      - name: Install Mocha
        run: |
         npm install --save-dev mocha
      - name: Run Tests
        run: npm test

      - name: Deploy
        env:
          API_KEY: ${{ secrets.MY_SECRET }}
        run: |
          echo "Deploying with API Key: $MY_SECRET"  
          # Insert your deployment script here